spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://korea-it.claegamki460.ap-northeast-2.rds.amazonaws.com:3306/springboot_db
    username: admin
    password: 1q2w3e4r!!
